blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/rootiest/obsidian-gpt-image-ocr/discussions
    about: Please use GitHub Discussions for general questions or ideas.
